project1/conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

project1/core/urls.py
from django.urls import path,include
from django.contrib.auth import views as auth_views

from .import views
from .form import loginForm
app_name ='core'

urlpatterns =[
    path('',views.index,name='index'),
    path('contact/',views.contact,name="contact"),
    path('signup/',views.signup,name='signup'),
    path('logout/',views.log_out,name='logout'),
    path('login/',auth_views.LoginView.as_view(template_name='core/login.html',authentication_form=loginForm),name="login"),
]

project1/dashboard/urls.py
from django.urls import path

from . import views

app_name='dashboard'

urlpatterns =[
    path('',views.index,name='index')
]

project1/items/urls.py
from django.urls import path,include

from .import views 

app_name='item'

urlpatterns = [
    path('',views.item,name='item'),
    path('new/',views.new,name='new'),
    path('<int:pk>/',views.detail,name='detail'),
    path('<int:pk>/delete/',views.delete,name='delete'),
    path('<int:pk>/edit/',views.edit,name='edit')
    ]

project1/project1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

from core.views import index,contact


urlpatterns = [
    path('',include('core.urls')),
    path('items/',include('items.urls')),
    path('dashboard/',include('dashboard.urls')),
    path('inbox/',include('conversation.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project1/core/models.py
from django.db import models

# Create your models here.

project1/core/views.py
from django.shortcuts import render,redirect
from items.models import Category,items
# Create your views here.
from .form import signupForm
from django.contrib.auth import logout

def log_out(request):
    logout(request)
    item=items.objects.filter(is_sold=False)[0:6]
    Categories=Category.objects.all()

    return render(request,'core/index.html',{
        'categories':Categories,
        'items':item,
    })

def index(request):
    item=items.objects.filter(is_sold=False)[0:6]
    Categories=Category.objects.all()

    return render(request,'core/index.html',{
        'categories':Categories,
        'items':item,
    })

def contact(request):
    return render(request,'core/contact.html')


def signup(request):
    if request.method=='POST':
        form=signupForm(request.POST)
        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:
        form = signupForm
    return render(request,'core/signup.html',{
        'form':form
    })

project1/core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>{% block title %}{% endblock %} | store</title>
</head>
<body>
    <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
        <a href="/" class="text-xl font-semibold">IESCE IEDC</a>
        <div class="space-x-6">
            <a href="{% url 'item:new' %}" class="text-lg font-semibold hover:text-gray-500"> New item</a>
            <a href="{% url 'item:item' %}" class="text-lg font-semibold hover:text-gray-500"> Browse</a>


           {% if request.user.is_authenticated %}
            <a href="{% url 'dashboard:index' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:text-teal-700">dashboad</a>
            <a href="{% url 'conversation:inbox' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:text-gray-700">inbox</a>
            <a href="{% url 'core:logout' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:text-gray-700">Log out</a>
            {% else %}
            <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:text-teal-700">Sign up</a>
            <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:text-gray-700">Log in</a>
            {% endif %}
        </div>
    </nav>
    <div class="py-6 px-6">
        {% block content %}
        {% endblock %}

    </div>
    <footer class="px-6 py-6 flex justify-between bg-gray-800">
        <div class="w-2/3 pr-10">
            <h3 class="mb-5 font-semibold text-gray-400">About</h3>
            <p class="text-lg text-gray-500">Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci placeat sequi non neque! Veniam unde culpa blanditiis quod alias cumque officia, illum dolores. Quibusdam nostrum praesentium quasi, esse suscipit minus!</p>
        </div>
        <div class="w-1/3">
            <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

            <ul class="space-y-2">
                <li> <a href="{% url 'core:index'  %}" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
                <li> <a href="{% url 'core:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
                <li> <a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy policy</a></li>
                <li> <a href="#" class="text-lg text-teal-500 hover:text-teal-700">Term of use</a></li>
            </ul>
        </div>
    </footer>
</body>
</html> 

project1/core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %}
contact
{% endblock %}

{% block content %}
welcome to contact page
{% endblock %}

project1/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}
welcome
{% endblock %}

{% block content %}
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center font-semibold">Newest items</h2>
    <div class="grid grid-cols-3 gap-3">
        {% for item in items %}
        <div>
            <a href="{%  url 'item:detail' item.id %}">
                <div>
                    <img src="{{ item.image.url }}" class="rounded-t-xl">
                </div>
                <div class="p-6 bg-white rounded-b-xl">
                    <h2 class="text-2xl font-semibold">{{ item.name }}</h2>
                    <p class="text-gray-500 font-semibold">price:{{ item.price }}</p>


                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center font-semibold">category</h2>
    <div class="grid grid-cols-3 gap-3">
        {% for category in categories %}
        <div>
            <a href="">
                <div class="p-6 bg-white rounded-b-xl">
                    <h2 class="text-2xl font-semibold">{{ category.name }}</h2>
                    <p class="text-gray-500 font-semibold">{{ category.items.count }} items</p>


                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

project1/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}
Log in
{% endblock %}


{% block content %}
<div class="w-1/2 my-6 mx-auto bg-gray-100 rounded-xl">
    <h1 class="mb-6 p-6 text-3xl">Log in</h1>
    <form action="." method="post" class="p-6" >
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="mb-3">
            <label for="" class="inline-block mb-2 font-semibold">Username</label><br>
            {{ form.username }}
        </div>
        
        <div class="mb-3">
            <label for="" class="inline-block mb-2 font-semibold"><Pre></Pre>Password</label><br>
            {{ form.password }}
        </div>
        {% if form.errors or form.non_field_errors %}
         <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for  field in form %}
                {{ field.errors }}
                {% endfor %}
         </div>
        {%  endif %}
        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Log in</button>
    </form>
</div>

{% endblock %}

project1/core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}
sign up
{% endblock %}


{% block content %}
<div class="w-1/2 my-6 mx-auto bg-gray-100 rounded-xl">
    <h1 class="mb-6 p-6 text-3xl">Sign up</h1>
    <form action="." method="post" class="p-6" >
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="mb-3">
            <label for="" class="inline-block mb-2 font-semibold">Username</label><br>
            {{ form.username }}
        </div>
        <div class="mb-3">
            <label for="" class="inline-block mb-2 font-semibold">Email</label><br>
            {{ form.email }}
        </div>
        <div class="mb-3">
            <label for="" class="inline-block mb-2 font-semibold"><Pre></Pre>Password</label><br>
            {{ form.password1 }}
        </div><div class="mb-3">
            <label for="" class="inline-block mb-2 font-semibold">Repeat assword</label><br>
            {{ form.password2 }}
        </div>
        {% if form.errors or form.non_field_errors %}
         <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for  field in form %}
                {{ field.errors }}
                {% endfor %}
         </div>
        {%  endif %}
        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">REGISTER</button>
    </form>
</div>

{% endblock %}