project1/conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

project1/core/urls.py
from django.urls import path,include
from django.contrib.auth import views as auth_views

from .import views
from .form import loginForm
app_name ='core'

urlpatterns =[
    path('',views.index,name='index'),
    path('contact/',views.contact,name="contact"),
    path('signup/',views.signup,name='signup'),
    path('logout/',views.log_out,name='logout'),
    path('login/',auth_views.LoginView.as_view(template_name='core/login.html',authentication_form=loginForm),name="login"),
]

project1/items/urls.py
from django.urls import path,include

from .import views 

app_name='item'

urlpatterns = [
    path('',views.item,name='item'),
    path('new/',views.new,name='new'),
    path('<int:pk>/',views.detail,name='detail'),
    path('<int:pk>/delete/',views.delete,name='delete'),
    path('<int:pk>/edit/',views.edit,name='edit')
    ]

project1/project1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

from core.views import index,contact


urlpatterns = [
    path('',include('core.urls')),
    path('items/',include('items.urls')),
    path('dashboard/',include('dashboard.urls')),
    path('inbox/',include('conversation.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project1/items/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255)


    class Meta:
        ordering =('name',)
        verbose_name_plural='categories'
    def __str__(self):
        return self.name

class items(models.Model):
    category = models.ForeignKey(Category,related_name='items',on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    decription =models.TextField(blank=True,null=True)
    price =models.FloatField()
    image = models.ImageField(upload_to='item_image',blank=True,null=True)
    is_sold = models.BooleanField(default=False)
    created_by =models.ForeignKey(User,related_name='item',on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    class Meta:
        verbose_name_plural='items'
    def __str__(self):
        return self.name

project1/items/forms.py
# forms.py
from django import forms
from .models import items  # Import your model

INPUT_CLASSES='w-full py-4 px-6 rounded-xl border'

class NewitemForm(forms.ModelForm):
    class Meta:
        model = items  # Specify the model
        fields = ('category','name','decription','price','image')  # List the fields to include in the form
    
        widgets ={
              'category':forms.Select(attrs={
              'class':INPUT_CLASSES
             }),
              'name':forms.TextInput(attrs={
              'class':INPUT_CLASSES
             }),
              'decription':forms.Textarea(attrs={
              'class':INPUT_CLASSES
             }),
              'price':forms.TextInput(attrs={
              'class':INPUT_CLASSES
             }),
              'image':forms.FileInput(attrs={
              'class':INPUT_CLASSES
             })
        }


class EdititemForm(forms.ModelForm):
    class Meta:
        model = items  # Specify the model
        fields = ('name','decription','price','image','is_sold')  # List the fields to include in the form
    
        widgets ={
              'name':forms.TextInput(attrs={
              'class':INPUT_CLASSES
             }),
              'decription':forms.Textarea(attrs={
              'class':INPUT_CLASSES
             }),
              'price':forms.TextInput(attrs={
              'class':INPUT_CLASSES
             }),
              'image':forms.FileInput(attrs={
              'class':INPUT_CLASSES
             })
        }

project1/items/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, get_object_or_404,redirect
from .models import items,Category
from .forms import NewitemForm,EdititemForm


def item(request):
    item= items.objects.filter(is_sold=False)
    query = request.GET.get('query','')
    category_id = request.GET.get('category', 0)
    Categories = Category.objects.all()

    if category_id:
        item = item.filter(category_id=category_id)

    if query:
        item=item.filter(Q(name__icontains=query) | Q(decription__icontains=query))

    return render(request,'item/item.html',{
        'items':item,
        'query':query,
        'categories':Categories,
        'category_id': int(category_id),
    })






# Create your views here.
def detail(request, pk):
    # Get the specific item
    item = get_object_or_404(items, pk=pk)
    # Use the item's category to filter related items
    related_items = items.objects.filter(category=item.category, is_sold=False).exclude(pk=pk)[0:3]

    return render(request, 'item/detail.html', {
        'item': item,
        'related_items': related_items,
    })

@login_required
def new(request):
    if request.method=='POST':
        form = NewitemForm(request.POST,request.FILES)


        if form.is_valid():
            item=form.save(commit=False)
            item.created_by=request.user
            item.save()
            return redirect('item:detail',pk=item.id)
    else:
        form = NewitemForm()

    return render(request,'item/new.html',{
        'form':form,
        'title':'ADD item',

    })

@login_required
def edit(request,pk):
    item = get_object_or_404(items, pk=pk,created_by=request.user)
    if request.method=='POST':
        form = EdititemForm(request.POST,request.FILES,instance=item)


        if form.is_valid():
            form.save()
            return redirect('item:detail',pk=item.id)
    else:
        form = EdititemForm(instance=item)

    return render(request,'item/new.html',{
        'form':form,
        'title':'Edit item',

    })


@login_required
def delete(request, pk):
    # Get the specific item
    item = get_object_or_404(items, pk=pk,created_by=request.user)
    item.delete()
    return redirect('dashboard:index')

project1/items/templates/item/detail.html
{% extends 'core/base.html' %}
{% block title %}
{{item.name}}
{% endblock %}



{% block content %}
<div class="grid grid-cols-5 gap-6">
    <div class="col-span-3">
        <img src="{{ item.image.url }}" class="rounded-xl">
    </div>
  

    <div class="p-6 col-span-2 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl font-semibold">{{ item.name }}</h1>
        
        <p class="text-gray-500 font-semibold"><strong>price:</strong>{{ item.price }}</p>
        <p class="text-gray-500 font-semibold"><strong>seller:</strong>{{ item.created_by }}</p>

    
        {% if item.decription %}
        <p class="text-gray-700 font-semibold break-words">
            <strong class="text-gray-500">Description:</strong><br>
            {{item.decription}}
        </p>
        {% endif %}

        {% if request.user == item.created_by %}
        <div class="mt-6 p-6 bg-white rounded-xl">
            <h3 class="font-semibold">This your item!</h3>
           
            <a href="{%  url 'item:edit' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg  font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Edit</a>
            <a href="{%  url 'item:delete' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg  font-semibold bg-red-500 text-white rounded-xl hover:bg-red-700">Delete</a>
        </div>

        {% else %}
             <a href="{% url 'conversation:new' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg  font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Contact seller</a>
        {% endif %}
     </div>

</div>

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center font-semibold">Related items</h2>
    <div class="grid grid-cols-3 gap-3">
        {% for item in related_items %}
        <div>
            <a href="{%  url 'item:detail' item.id %}">
                <div>
                    <img src="{{ item.image.url }}" class="rounded-t-xl">
                </div>
                <div class="p-6 bg-white rounded-b-xl">
                    <h2 class="text-2xl font-semibold">{{ item.name }}</h2>
                    <p class="text-gray-500 font-semibold">price:{{ item.price }}</p>


                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

project1/items/templates/item/item.html
{% extends 'core/base.html' %}
{% block title %}
Browse
{% endblock %}


{% block content %}
<div class="pb-6 grid grid-cols-4 gap-4 bg-gray-100">
    <div class="col-span-1">
        <form action="{% url 'item:item' %}" method="get">
            <input name="query" class="w-full py-4 px-6 border rounded-xl" type="text" value="{{ query }}" placeholder="find something!">
            <button class="px-8 py-4 mt-3 text-lg font-semibold text-white bg-teal-500 rounded-xl hover:bg-teal-700" >Search !</button>
        </form>


        <hr class="my-6">
        <p class="font-semibold">Categories</p>

            <ul>
                {% for category in categories %}
                    <li class="py-2 px-2 rounded-xl{% if category.id == category_id %} bg-gray-200{% endif %}">
                        <a href="{% url 'item:item' %}?query={{ query }}&category={{ category.id }}">{{ category.name }}</a>
                    </li>
                {% endfor %}
            </ul>
            <hr class="my-6">

            <p class="font-semibold">Clear filters</p>

            <ul>
                <li><a href="{% url 'item:item' %}" class="mt-2 py-4 px-8 inline-block bg-yellow-500 text-lg rounded-xl text-white">Clear</a></li>
            </ul>
     
    </div>
    <div class="col-span-3">
        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
            <div>
                <a href="{%  url 'item:detail' item.id %}">
                    <div>
                        <img src="{{ item.image.url }}" class="rounded-t-xl">
                    </div>
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl font-semibold">{{ item.name }}</h2>
                        <p class="text-gray-500 font-semibold">price:{{ item.price }}</p>
    
    
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>

    </div>
</div>



{% endblock %}

project1/items/templates/item/new.html
{% extends 'core/base.html' %}
{% block title %}
{{title  }}
{% endblock %}




{% block content %}
<h1 class="mb-6 text-3xl">{{ title}}</h1>

<form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}
    
    <div class="space-y-4">
        {{ form.as_p }}

    </div>
    {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for  field in form %}
                {{ field.errors }}
            {% endfor %}
        </div>
    {%  endif %}
        <button class="py-4 px-8 mt-6 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Add item</button>
</form>
{% endblock %}